[package]
name = "practice"
version = "0.1.0"
edition = "2021"

[dependencies]
#futures = "0.3.30"
tokio = { version = "1.36.0", features = ["full"] }
reqwest = "0.11.26"
hyper = "0.14.28"
hyper-tls = "0.5.0"
#reqwest = { version = "0.11.25", features = ["json"] }
